export { Console } from "./homedecor/console.jsx"
export { Bookcase } from "./homedecor/bookshelf.jsx"
export { Armchair, Ottoman, FloorLamp } from "./homedecor/seating.jsx"
export { SideTable, RoundTable, RealBook } from "./homedecor/tables.jsx"
export { WallClock, WallFrames, WindowCurtains } from "./homedecor/wall.jsx"
export { Television } from "./homedecor/tv.jsx"
export { HangingPlant } from "./homedecor/hanging.jsx"
export { LesehanTable, RectRug, RoundRug } from "./homedecor/lesehan.jsx"
export { Mug, GreenTea, Mixue } from "./homedecor/drinks.jsx"
export { PresidentPortrait } from "./homedecor/portrait.jsx"
